version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../airbnb_deployment_package.zip.
      - cd ..
      - zip -g airbnb_deployment_package.zip  airbnb_booking_mockdata.py airbnb_enrichment.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp airbnb_deployment_package.zip s3://airbnb-deployment-package
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket airbnb-deployment-package --s3-key airbnb_deployment_package.zip
      - echo "Deployment complete!"